<footer id="footer" class="wrapper">
  <div class="inner">
  <!--   <div id="footer-copyright">
    &copy; {{ moment(Date.now()).year() }} <a href="#" target="_blank">Xlink</a><br>
  </div> -->
    <div id="footer-links">
		<a href="/overview/index.html" class="footer-link">文档</a>
		<a href="#" class="footer-link">SDK下载</a>
		<a href="#" class="footer-link">价格</a>
		<a href="#" class="footer-link">联系我们</a>
		<a href="#" class="footer-link">客服工单</a>
    </div>
  </div>
</footer>
