<footer id="footer" class="wrapper">
  <div class="inner">
    {# <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a href="#" target="_blank">Xlink</a><br>
    </div> #}
    <div id="footer-links">
  		<a href="/faq" class="footer-link">Q &amp; A</a>
  		<a href="/debug" class="footer-link">调试助手</a>
  		<a href="/download" class="footer-link">SDK下载</a>
  		<a href="/api" class="footer-link">API文档</a>
    </div>
  </div>
</footer>
